### ISSUE TITLE
App crashes when it is brought back to foreground when it's running in background.

### ISSUE THREAD

**Issue by lecanhhiep** [CariusLars/ar_flutter_plugin#38]
Hi @CariusLars ,

We're facing the crash issue on Android 7.1 (Note 8). App is always crash when it run at background and bring back to foreground (onPause -> onResume) and throw this exception:

E/AndroidRuntime(18270): java.lang.NullPointerException: throw with null exception
E/AndroidRuntime(18270): 	at com.google.ar.sceneform.utilities.Preconditions.checkNotNull(SourceFile:3)
E/AndroidRuntime(18270): 	at com.google.ar.sceneform.Scene.setUseHdrLightEstimate(SourceFile:101)
E/AndroidRuntime(18270): 	at com.google.ar.sceneform.ArSceneView.updateNormalLightEstimate(SourceFile:204)
E/AndroidRuntime(18270): 	at com.google.ar.sceneform.ArSceneView.updateLightEstimate(SourceFile:136)
E/AndroidRuntime(18270): 	at com.google.ar.sceneform.ArSceneView.onBeginFrame(SourceFile:124)
E/AndroidRuntime(18270): 	at com.google.ar.sceneform.SceneView.doFrameNoRepost(SourceFile:90)
E/AndroidRuntime(18270): 	at com.google.ar.sceneform.SceneView.doFrame(SourceFile:86)
E/AndroidRuntime(18270): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:928)
E/AndroidRuntime(18270): 	at android.view.Choreographer.doCallbacks(Choreographer.java:705)
E/AndroidRuntime(18270): 	at android.view.Choreographer.doFrame(Choreographer.java:637)
E/AndroidRuntime(18270): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:916)
E/AndroidRuntime(18270): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime(18270): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(18270): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(18270): 	at android.app.ActivityThread.main(ActivityThread.java:6823)
E/AndroidRuntime(18270): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18270): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
E/AndroidRuntime(18270): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

I have tried by adding:

  @override
  void dispose() {
try {
  print("Removeing node");
    if (this.localObjectNode != null) {
      this.arObjectManager?.removeNode(this.localObjectNode!);
      this.localObjectNode = null;
    }
  } catch(err, stackstrace) {
  print(stackstrace);
  }

  super.dispose();
  }

 when close the AR popup dialog, but when I leave the app running at background and bring it back to foreground, the above exception is still happening and app crash.

Could you please give us some advice to fix it?

Thanks,

**Comment by CariusLars** [comment]
Hey @lecanhhiep and sorry for the late answer! Does this happen with the example application of the plugin or with your own app that utilizes the plugin? 
I've just tried with the example application on my Android9 device and I can but the app into the background and back to the foreground without it crashing, so it would be good to have some more information on what system and what code you use as well as the exact scenario in which the crash happens.
To debug this issue, I'd suggest placing some breakpoints into the `onResume()` function (line 310 onwards) of the [AndroidARView](https://github.com/CariusLars/ar_flutter_plugin/blob/main/android/src/main/kotlin/io/carius/lars/ar_flutter_plugin/AndroidARView.kt) and skipping through them to see which line causes the crash.
Let me know if you find which object or line causes the crash and I can look into it some more!
Best regards
Lars

**Comment by CariusLars** [comment]
Hey guys, sorry for the late reply on this...
It seems like someone found a solution to this problem: [https://github.com/CariusLars/ar_flutter_plugin/issues/59](https://github.com/CariusLars/ar_flutter_plugin/issues/59)
As soon as the PR is out I will review this and publish a new release version, hopefully that will fix your issues!
