### ISSUE TITLE
Launching the plugin on the Android emulator(Android 12) leads to a "failed to create ar session" error

### ISSUE THREAD

**Issue by svyazist2005** [CariusLars/ar_flutter_plugin#74]
Launching the plugin on the Android emulator(Android 12) leads to a "failed to create ar session" error

environment:
ar_flutter_plugin: ^0.6.1
Flutter (Channel master, 2.6.0-12.0.pre.675, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-UA)
Xcode - develop for iOS and macOS (Xcode 12.4)
VS Code (version 1.48.2)

Failed to load native library [packageName=com.google.ar.core,libraryName=arcore_c] from remote package:
![image](https://user-images.githubusercontent.com/16213879/148542930-a539eddc-cd32-4fbc-a30e-60664021395c.png)

D/io.carius.lars.ar_flutter_plugin.AndroidARView( 5000): Initializing AndroidARView
I/SceneView( 5000): Optional library com.google.ar.sceneform.animation not present. Sceneform animation disabled
D/io.carius.lars.ar_flutter_plugin.AndroidARView( 5000): ARSceneView session is null. Trying to initialize
I/third_party/arcore/ar/core/android/sdk/session_create.cc( 5000): Entering ArSession_createWithFeatures
I/third_party/arcore/ar/core/android/sdk/session_create.cc( 5000): ARCore Version: SDK build name: 1.22
I/third_party/arcore/ar/core/android/sdk/session_create.cc( 5000): ARCore Version: APK version code: 213210293
I/third_party/arcore/ar/core/android/sdk/session_create.cc( 5000): Dynamite load ok.
I/third_party/arcore/java/com/google/vr/dynamite/client/native/dynamite_client.cc( 5000): Attempting to load native library arcore_c from package com.google.ar.core
E/DynamiteClient( 5000): Failed to load native library [packageName=com.google.ar.core,libraryName=arcore_c] from remote package:
E/DynamiteClient( 5000):   
E/DynamiteClient( 5000): java.lang.IllegalStateException: Library arcore_c loaded in the same classloader context as library null
E/DynamiteClient( 5000):        at com.google.vr.dynamite.NativeLibraryLoader.initializeAndLoadNativeLibrary(PG:1)
E/DynamiteClient( 5000):        at faa.A(PG:6)
E/DynamiteClient( 5000):        at abm.onTransact(PG:3)
E/DynamiteClient( 5000):        at android.os.Binder.transact(Binder.java:1064)
E/DynamiteClient( 5000):        at com.google.a.a.a.b(BaseProxy.java:2)
E/DynamiteClient( 5000):        at com.google.vr.dynamite.client.b.initializeAndLoadNativeLibrary(INativeLibraryLoader.java:3)
E/DynamiteClient( 5000):        at com.google.vr.dynamite.client.DynamiteClient.loadNativeRemoteLibrary(DynamiteClient.java:8)
E/DynamiteClient( 5000):        at com.google.ar.core.Session.nativeCreateSessionAndWrapperWithFeatures(Native Method)
E/DynamiteClient( 5000):        at com.google.ar.core.Session.<init>(Session.java:11)
E/DynamiteClient( 5000):        at com.google.ar.core.Session.<init>(Session.java:4)
E/DynamiteClient( 5000):        at io.carius.lars.ar_flutter_plugin.AndroidARView.onResume(AndroidARView.kt:395)
E/DynamiteClient( 5000):        at io.carius.lars.ar_flutter_plugin.AndroidARView.<init>(AndroidARView.kt:337)
E/DynamiteClient( 5000):        at io.carius.lars.ar_flutter_plugin.AndroidARViewFactory.create(AndroidARViewFactory.kt:14)
E/DynamiteClient( 5000):        at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:186)
E/DynamiteClient( 5000):        at android.app.Dialog.dispatchOnCreate(Dialog.java:424)
E/DynamiteClient( 5000):        at android.app.Dialog.show(Dialog.java:318)
E/DynamiteClient( 5000):        at android.app.Presentation.show(Presentation.java:279)
E/DynamiteClient( 5000):        at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
E/DynamiteClient( 5000):        at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
E/DynamiteClient( 5000):        at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:212)
E/DynamiteClient( 5000):        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:107)
E/DynamiteClient( 5000):        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/DynamiteClient( 5000):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/DynamiteClient( 5000):        at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/DynamiteClient( 5000):        at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/DynamiteClient( 5000):        at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/DynamiteClient( 5000):        at android.os.Handler.handleCallback(Handler.java:938)
E/DynamiteClient( 5000):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/DynamiteClient( 5000):        at android.os.Looper.loopOnce(Looper.java:201)
E/DynamiteClient( 5000):        at android.os.Looper.loop(Looper.java:288)
E/DynamiteClient( 5000):        at android.app.ActivityThread.main(ActivityThread.java:7839)
E/DynamiteClient( 5000):        at java.lang.reflect.Method.invoke(Native Method)
E/DynamiteClient( 5000):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/DynamiteClient( 5000):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
I/third_party/arcore/java/com/google/vr/dynamite/client/native/dynamite_client.cc( 5000): Dynamite::LoadNativeRemoteLibrary handle=0
E/third_party/arcore/ar/core/android/sdk/session_create.cc( 5000): Dynamite failed to load remote library
E/third_party/arcore/ar/core/android/sdk/session_create.cc( 5000): LoadSymbolsDynamite returning AR_ERROR_FATAL.
E/third_party/arcore/ar/core/android/sdk/session_create.cc( 5000): LoadSymbols returning status.

**Comment by CariusLars** [comment]
Hey @svyazist2005 , did you follow [this guide](https://developers.google.com/ar/develop/java/emulator)?
